export const FETCH_ACCOUNT = 'FETCH_ACCOUNT';
export const FETCH_ACCOUNT_SUCCESS = 'FETCH_ACCOUNT_SUCCESS';
export const FETCH_ACCOUNT_FAILED = 'FETCH_ACCOUNT_FAILED';

export const FETCH_ACCOUNTS = 'FETCH_ACCOUNTS';
export const FETCH_ACCOUNTS_SUCCESS = 'FETCH_ACCOUNTS_SUCCESS';
export const FETCH_ACCOUNTS_FAILED = 'FETCH_ACCOUNTS_FAILED';

export const RESET_ACCOUNTS = 'RESET_ACCOUNTS';

export const SET_ACCOUNT_MAP = 'SET_ACCOUNT_MAP';
export const SET_ACCOUNT_OPTIONS = 'SET_ACCOUNT_OPTIONS';
