export const BLOG_FETCHING = 'BLOG_FETCHING';
export const BLOG_FETCH_SUCCESS = 'BLOG_FETCH_SUCCESS';
export const BLOG_FETCH_FAILED = 'BLOG_FETCH_FAILED';

export const BLOG_PAGE_NEXT = 'BLOG_PAGE_NEXT';
export const BLOG_PAGE_PREV = 'BLOG_PAGE_PREV';

export const POSTS_FETCHING = 'POSTS_FETCHING';
export const POSTS_FETCH_SUCCESS = 'POSTS_FETCH_SUCCESS';
export const POSTS_FETCH_FAILED = 'POSTS_FETCH_FAILED';

export const POST_FETCHING = 'POST_FETCHING';
export const POST_FETCH_SUCCESS = 'POST_FETCH_SUCCESS';
export const POST_FETCH_FAILED = 'POST_FETCH_FAILED';
