export const FETCHING_BLOG = 'FETCHING_BLOG';
export const FETCH_BLOG_SUCCESS = 'FETCH_BLOG_SUCCESS';
export const FETCH_BLOG_FAILED = 'FETCH_BLOG_FAILED';

export const BLOG_PAGE_NEXT = 'BLOG_PAGE_NEXT';
export const BLOG_PAGE_PREV = 'BLOG_PAGE_PREV';

export const FETCHING_POSTS = 'FETCHING_POSTS';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAILED = 'FETCH_POSTS_FAILED';

export const FETCHING_POST = 'FETCHING_POST';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_FAILED = 'FETCH_POST_FAILED';
