export const POSTING_CONSULTATION = 'POSTING_CONSULTATION';
export const POST_CONSULTATION_SUCCESS = 'POST_CONSULTATION_SUCCESS';
export const POST_CONSULTATION_FAILED = 'POST_CONSULTATION_FAILED';
export const RESET_CONSULTATION = 'RESET_CONSULTATION';
