export const POSTING_CONTACT = 'POSTING_CONTACT';
export const POST_CONTACT_SUCCESS = 'POST_CONTACT_SUCCESS';
export const POST_CONTACT_FAILED = 'POST_CONTACT_FAILED';
export const RESET_CONTACT = 'RESET_CONTACT';
