export const CONTACT_POSTING = 'CONTACT_POSTING';
export const CONTACT_POST_SUCCESS = 'CONTACT_POST_SUCCESS';
export const CONTACT_POST_FAILED = 'CONTACT_POST_FAILED';
export const CONTACT_RESET = 'CONTACT_RESET';
