export const FETCHING_IDENTITY = 'FETCHING_IDENTITY';
export const FETCH_IDENTITY_SUCCESS = 'FETCH_IDENTITY_SUCCESS';
export const FETCH_IDENTITY_FAILED = 'FETCH_IDENTITY_FAILED';
export const RESET_IDENTITY = 'RESET_IDENTITY';
