








export const FEATURED_FETCHING = 'FEATURED_FETCHING';
export const FEATURED_FETCH_SUCCESS = 'FEATURED_FETCH_SUCCESS';
export const FEATURED_FETCH_FAILED = 'FEATURED_FETCH_FAILED';

export const TESTIMONIALS_FETCHING = 'TESTIMONIALS_FETCHING';
export const TESTIMONIALS_FETCH_SUCCESS = 'TESTIMONIALS_FETCH_SUCCESS';
export const TESTIMONIALS_FETCH_FAILED = 'TESTIMONIALS_FETCH_FAILED';

export const BLOG_FETCHING = 'BLOG_FETCHING';
export const BLOG_FETCH_SUCCESS = 'BLOG_FETCH_SUCCESS';
export const BLOG_FETCH_FAILED = 'BLOG_FETCH_FAILED';
export const BLOG_PAGE_NEXT = 'BLOG_PAGE_NEXT';
export const BLOG_PAGE_PREV = 'BLOG_PAGE_PREV';

export const POSTS_FETCHING = 'POSTS_FETCHING';
export const POSTS_FETCH_SUCCESS = 'POSTS_FETCH_SUCCESS';
export const POSTS_FETCH_FAILED = 'POSTS_FETCH_FAILED';

export const POST_FETCHING = 'POST_FETCHING';
export const POST_FETCH_SUCCESS = 'POST_FETCH_SUCCESS';
export const POST_FETCH_FAILED = 'POST_FETCH_FAILED';

export const PORTFOLIO_FETCHING = 'PORTFOLIO_FETCHING';
export const PORTFOLIO_FETCH_SUCCESS = 'PORTFOLIO_FETCH_SUCCESS';
export const PORTFOLIO_FETCH_FAILED = 'PORTFOLIO_FETCH_FAILED';
export const PORTFOLIO_SET_SELECTED = 'PORTFOLIO_SET_SELECTED';

export const CONTACT_POSTING = 'CONTACT_POSTING';
export const CONTACT_POST_SUCCESS = 'CONTACT_POST_SUCCESS';
export const CONTACT_POST_FAILED = 'CONTACT_POST_FAILED';
export const CONTACT_RESET = 'CONTACT_RESET';

export const SUBSCRIBE_POSTING = 'SUBSCRIBE_POSTING';
export const SUBSCRIBE_POST_SUCCESS = 'SUBSCRIBE_POST_SUCCESS';
export const SUBSCRIBE_POST_FAILED = 'SUBSCRIBE_POST_FAILED';
export const SUBSCRIBE_SHOW = 'SUBSCRIBE_SHOW';
export const SUBSCRIBE_HIDE = 'SUBSCRIBE_HIDE';
