

const SUBSCRIBE_SHOW = 'SUBSCRIBE_SHOW';
const SUBSCRIBE_HIDE = 'SUBSCRIBE_HIDE';
const SUBSCRIBE_POSTING = 'SUBSCRIBE_POSTING';
const SUBSCRIBE_POST_SUCCESS = 'SUBSCRIBE_POST_SUCCESS';
const SUBSCRIBE_POST_FAILED = 'SUBSCRIBE_POST_FAILED';
