export const FETCHING_PORTFOLIO = 'FETCHING_PORTFOLIO';
export const FETCH_PORTFOLIO_SUCCESS = 'FETCH_PORTFOLIO_SUCCESS';
export const FETCH_PORTFOLIO_FAILED = 'FETCH_PORTFOLIO_FAILED';
export const SET_SELECTED_PORTFOLIO = 'SET_SELECTED_PORTFOLIO';
