export const PORTFOLIO_FETCHING = 'PORTFOLIO_FETCHING';
export const PORTFOLIO_FETCH_SUCCESS = 'PORTFOLIO_FETCH_SUCCESS';
export const PORTFOLIO_FETCH_FAILED = 'PORTFOLIO_FETCH_FAILED';
export const PORTFOLIO_SET_SELECTED = 'PORTFOLIO_SET_SELECTED';
