export const FETCHING_PROJECT = 'FETCHING_PROJECT';
export const FETCH_PROJECT_SUCCESS = 'FETCH_PROJECT_SUCCESS';
export const FETCH_PROJECT_FAILED = 'FETCH_PROJECT_FAILED';
export const RESET_PROJECTS = 'RESET_PROJECTS';
export const SET_PROJECT_DIRECTORY = 'SET_PROJECT_DIRECTORY';
