export const MERGE_INCOMING_REVIEWS = 'MERGE_INCOMING_REVIEWS';

export const UPDATE_REVIEW = 'UPDATE_REVIEW';
export const UPDATE_REVIEW_SUCCESS = 'UPDATE_REVIEW_SUCCESS';
export const UPDATE_REVIEW_FAILED = 'UPDATE_REVIEW_FAILED';

export const REVIEW_OPTION_SET_SELECTED = 'REVIEW_OPTION_SET_SELECTED';
export const REVIEW_OPTION_CLEAR_SELECTED = 'REVIEW_OPTION_CLEAR_SELECTED';
export const REVIEW_OPTION_ADD_COMMENT = 'REVIEW_OPTION_ADD_COMMENT';
export const REVIEW_OPTION_SET_VIEWING = 'REVIEW_OPTION_SET_VIEWING';

export const REVIEW_REQUEST_REVISION = 'REVIEW_REQUEST_REVISION';
export const REVIEW_REQUEST_DELIVERABLES = 'REVIEW_REQUEST_DELIVERABLES';
export const REVIEW_REQUEST_CANCELED = 'REVIEW_REQUEST_CANCELED';

export const REVIEW_COMMENTS_TOGGLED = 'REVIEW_COMMENTS_TOGGLED';
export const REVIEW_STEP_TOGGLED = 'REVIEW_STEP_TOGGLED';

export const REVIEW_SHOW_FEEDBACK = 'REVIEW_SHOW_FEEDBACK';
export const REVIEW_HIDE_FEEDBACK = 'REVIEW_HIDE_FEEDBACK';
export const REVIEW_SHOW_APPROVAL = 'REVIEW_SHOW_APPROVAL';
export const REVIEW_HIDE_APPROVAL = 'REVIEW_HIDE_APPROVAL';

export const REVIEW_UI_RESET = 'REVIEW_UI_RESET';
