export const SETTINGS_UPDATE_EMAIL = 'SETTINGS_UPDATE_EMAIL';
export const SETTINGS_UPDATE_EMAIL_SUCCESS = 'SETTINGS_UPDATE_EMAIL_SUCCESS';
export const SETTINGS_UPDATE_EMAIL_FAILED = 'SETTINGS_UPDATE_EMAIL_FAILED';

export const SETTINGS_UPDATE_USERNAME = 'SETTINGS_UPDATE_USERNAME';
export const SETTINGS_UPDATE_USERNAME_SUCCESS = 'SETTINGS_UPDATE_USERNAME_SUCCESS';
export const SETTINGS_UPDATE_USERNAME_FAILED = 'SETTINGS_UPDATE_USERNAME_FAILED';

export const SETTINGS_UPDATE_PASSWORD = 'SETTINGS_UPDATE_PASSWORD';
export const SETTINGS_UPDATE_PASSWORD_SUCCESS = 'SETTINGS_UPDATE_PASSWORD_SUCCESS';
export const SETTINGS_UPDATE_PASSWORD_FAILED = 'SETTINGS_UPDATE_PASSWORD_FAILED';
