export const SUBSCRIBE_POSTING = 'SUBSCRIBE_POSTING';
export const SUBSCRIBE_POST_SUCCESS = 'SUBSCRIBE_POST_SUCCESS';
export const SUBSCRIBE_POST_FAILED = 'SUBSCRIBE_POST_FAILED';
export const SUBSCRIBE_SHOW = 'SUBSCRIBE_SHOW';
export const SUBSCRIBE_HIDE = 'SUBSCRIBE_HIDE';
