export const POSTING_SUBSCRIBE = 'POSTING_SUBSCRIBE';
export const POST_SUBSCRIBE_SUCCESS = 'POST_SUBSCRIBE_SUCCESS';
export const POST_SUBSCRIBE_FAILED = 'POST_SUBSCRIBE_FAILED';
export const SHOW_SUBSCRIBE = 'SHOW_SUBSCRIBE';
export const HIDE_SUBSCRIBE = 'HIDE_SUBSCRIBE';
