export const TESTIMONIALS_FETCHING = 'TESTIMONIALS_FETCHING';
export const TESTIMONIALS_FETCH_SUCCESS = 'TESTIMONIALS_FETCH_SUCCESS';
export const TESTIMONIALS_FETCH_FAILED = 'TESTIMONIALS_FETCH_FAILED';
