
const TOKEN_REFRESH_REQUESTED = 'TOKEN_REFRESH_REQUESTED';
const TOKEN_REFRESH_REQUEST_SUCCESS = 'TOKEN_REFRESH_REQUEST_SUCCESS';
const TOKEN_REFRESH_REQUEST_FAILED = 'TOKEN_REFRESH_REQUEST_FAILED';

const TOKEN_ACCESS_REQUESTED = 'TOKEN_ACCESS_REQUESTED';
const TOKEN_ACCESS_REQUESTED_SUCCESS = 'TOKEN_ACCESS_REQUESTED_SUCCESS';
const TOKEN_ACCESS_REQUESTED_FAILED = 'TOKEN_ACCESS_REQUESTED_FAILED';
