export const FETCHING_TESTIMONIALS = 'FETCHING_TESTIMONIALS';
export const FETCH_TESTIMONIALS_SUCCESS = 'FETCH_TESTIMONIALS_SUCCESS';
export const FETCH_TESTIMONIALS_FAILED = 'FETCH_TESTIMONIALS_FAILED';
