// <auto-generated />
namespace Skyberry.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class designreviewupdates : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(designreviewupdates));
        
        string IMigrationMetadata.Id
        {
            get { return "201509152159049_design-review-updates"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
