export const SHOW_CHANGE_EMAIL = 'SHOW_CHANGE_EMAIL';
export const HIDE_CHANGE_EMAIL = 'HIDE_CHANGE_EMAIL';

export const SHOW_CHANGE_PASSWORD = 'SHOW_CHANGE_PASSWORD';
export const HIDE_CHANGE_PASSWORD = 'HIDE_CHANGE_PASSWORD';

export const SHOW_CHANGE_USERNAME = 'SHOW_CHANGE_USERNAME';
export const HIDE_CHANGE_USERNAME = 'HIDE_CHANGE_USERNAME';
