export const CHANGE_EMAIL_SHOW = 'CHANGE_EMAIL_SHOW';
export const CHANGE_EMAIL_HIDE = 'CHANGE_EMAIL_HIDE';

export const CHANGE_PASSWORD_SHOW = 'CHANGE_PASSWORD_SHOW';
export const CHANGE_PASSWORD_HIDE = 'CHANGE_PASSWORD_HIDE';

export const CHANGE_USERNAME_SHOW = 'CHANGE_USERNAME_SHOW';
export const CHANGE_USERNAME_HIDE = 'CHANGE_USERNAME_HIDE';
