export const UPDATING_EMAIL = 'UPDATING_EMAIL';
export const UPDATE_EMAIL_SUCCESS = 'UPDATE_EMAIL_SUCCESS';
export const UPDATE_EMAIL_FAILED = 'UPDATE_EMAIL_FAILED';
export const UPDATE_EMAIL_RESET = 'UPDATE_EMAIL_RESET';
