export const UPDATING_USERNAME = 'UPDATE_USERNAME';
export const UPDATE_USERNAME_SUCCESS = 'UPDATE_USERNAME_SUCCESS';
export const UPDATE_USERNAME_FAILED = 'UPDATE_USERNAME_FAILED';
export const UPDATE_USERNAME_RESET = 'UPDATE_USERNAME_RESET';
